enum ActionType {
  GET_ALL_CHARACTERS = 'GET_ALL_CHARACTERS',
  GET_ALL_CHARACTERS_SUCCESS = 'GET_ALL_CHARACTERS_SUCCESS',
  GET_ALL_CHARACTERS_FAILED = 'GET_ALL_CHARACTERS_FAILED',
}

export default ActionType;
