enum ActionTypes {
  GET_ALL_EPISODES = 'GET_ALL_EPISODES',
  GET_ALL_EPISODES_SUCCESS = 'GET_ALL_EPISODES_SUCCESS',
  GET_ALL_EPISODES_FAILED = 'GET_ALL_EPISODES_FAILED',
}

export default ActionTypes;
